name: C++ build
description: build source files
inputs:
  build_type:
    description: 'cmake build type'
    required: false
    default: 'Debug'

runs:
  using: "composite"
  steps:
    - name: "install lcov for coverage"
      run: sudo apt install lcov
      shell: bash

    - name: "generate build files for ${{inputs.build_type}}"
      run: cmake -S . -B build_${{inputs.build_type}} -DCMAKE_BUILD_TYPE=${{inputs.build_type}}
      shell: bash

    - name: "cmake build targets"
      run: cmake --build build_${{inputs.build_type}}
      shell: bash
