name: C++ build
description: build source files
inputs:
  build_type:
    description: 'cmake build type'
    required: false
    default: 'Debug'
env:
  CACHE_DIR: cmake

runs:
  using: "composite"
  steps:
    - name: "install lcov for coverage"
      run: sudo apt install lcov
      shell: bash

    - name: "check cache CPM"
      id: cache-cpm
      uses: actions/cache@v3
      with:
        path: |
          ${{ CACH_DIR }}/CPM.cmake
          ${{ CACH_DIR }}/CodeCoverage.cmake
          ${{ CACH_DIR }}/catch2
        key: ${{ hashFiles('CMakeLists.txt') }}--cpm

    - name: "generate build files for ${{inputs.build_type}}"
      run: cmake -S . -B build_${{inputs.build_type}} -DCMAKE_BUILD_TYPE=${{inputs.build_type}} -DCPM_SOURCE_CACHE=$CACHE_DIR
      shell: bash

    - name: "cmake build targets"
      run: cmake --build build_${{inputs.build_type}}
      shell: bash

