name: C++ build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: "checkout repo"
      uses: actions/checkout@v3

    - name: "build"
      uses: ./.github/actions

    - name: "test"
      working-directory: ./build
      run: make test

    - name: "code coverage"
      working-directory: ./build
      run: make coverage

    - name: "comment coverage"
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        lcov-file: ./build/coverage.info
        delete-old-comments: true
        filter-changed-files: true
        title: "Code Coverage Report"
      if: ${{ github.event_name == 'pull_request' }}
